#!/bin/bash
# Job name
#PBS -N matrixTransposeJob
# Output files
#PBS -o ./matrixTransposeJob.o
#PBS -e ./matrixTransposeJobErrors.e
# Queue name
#PBS -q short_cpuQ
# Set the maximum wall time
#PBS -l walltime=0:10:00
# Number of nodes, cpus, mpi processors and amount of memory
#PBS -l select=1:ncpus=64:mem=1Gb

# Modules for C
module load gcc91
gcc() {
    gcc-9.1.0 "$@"
}
gcc --version
# Select the working directory
cd /home/username/H1

# Compilation and executions of different N sizes with different flags

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITHOUT FLAGS WITH N = 4096+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
gcc -fopenmp -o h1 matrixTranspose.c

./h1 4096

echo -e

echo  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITHOUT FLAGS WITH N = 2048+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

./h1 2048

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITHOUT FLAGS WITH N = 1024+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

./h1 1024

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITHOUT FLAGS WITH N = 512+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

./h1 512

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITHOUT FLAGS WITH N = 256+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

./h1 256

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITH -O FLAG WITH N = 4096+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

gcc -fopenmp -O -o h1 matrixTranspose.c

./h1 4096

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITH -Os FLAG WITH N = 4096+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

gcc -fopenmp -Os -o h1 matrixTranspose.c

./h1 4096

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITH -O1 FLAG WITH N = 4096+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
gcc -fopenmp -O1 -o h1 matrixTranspose.c

./h1 4096

echo -e

echo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITH -O2 FLAG WITH N = 4096+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
gcc -fopenmp -O2 -o h1 matrixTranspose.c

./h1 4096

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITH -O FLAG WITH N = 2048+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

gcc -fopenmp -O -o h1 matrixTranspose.c

./h1 2048

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITH -Os FLAG WITH N = 2048+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

gcc -fopenmp -Os -o h1 matrixTranspose.c

./h1 2048

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITH -O1 FLAG WITH N = 2048+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

gcc -fopenmp -O1 -o h1 matrixTranspose.c

./h1 2048

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITH -Os FLAG WITH N = 1024+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

gcc -fopenmp -Os -o h1 matrixTranspose.c

./h1 1024

echo -e

echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++EXECUTION WITH -O1 FLAG WITH N = 1024+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
gcc -fopenmp -O1 -o h1 matrixTranspose.c

./h1 1024

echo -e

